//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.0
//     from Packages/com.n04h.techartlibrary/Base/Players/Plane/Plane_Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Packages/com.n04h.techartlibrary/Base/Players/Plane/Plane_Controls.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @Plane_Controls: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @Plane_Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Plane_Controls"",
    ""maps"": [
        {
            ""name"": ""Plane_Action_Map"",
            ""id"": ""ad5492f3-8439-44a8-8ee9-41691c9ab66c"",
            ""actions"": [
                {
                    ""name"": ""PitchUp"",
                    ""type"": ""Button"",
                    ""id"": ""04e74356-1e26-4a86-9eeb-3d78e0bc2f51"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PitchDown"",
                    ""type"": ""Button"",
                    ""id"": ""b00f6679-37b5-4c4e-af67-6315d01134d2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RollRight"",
                    ""type"": ""Button"",
                    ""id"": ""d62d328b-3bce-49e6-83bd-6ffe0df43010"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RollLeft"",
                    ""type"": ""Button"",
                    ""id"": ""b68360f8-5eff-4c8b-856c-3754dd62d015"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""YawRight"",
                    ""type"": ""Button"",
                    ""id"": ""421019d2-db7c-496e-965d-195def4d6c66"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""YawLeft"",
                    ""type"": ""Button"",
                    ""id"": ""91d1f571-37a4-49ea-8c44-020a5e2157a0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left"",
                    ""type"": ""Button"",
                    ""id"": ""aaba9300-5351-4a35-b40c-fed2db7ad4ea"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Front/Back"",
                    ""type"": ""Value"",
                    ""id"": ""e251d93f-2f4f-4495-bfbe-dd07c73aedc6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Yaw1"",
                    ""type"": ""Value"",
                    ""id"": ""aaec1c49-dcde-44fe-a822-d55d04d273e3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Handbrake"",
                    ""type"": ""Button"",
                    ""id"": ""8f1d36d0-70d1-4a75-bfb9-a5486c13fe2a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""16fe58d6-9c5a-47d0-9523-63cd6003c135"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""c5b6ddab-c68f-4250-be48-a1c0389ccee3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Throttle"",
                    ""type"": ""Button"",
                    ""id"": ""877d443c-2e2a-4597-b7ba-074b74b3a2d9"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d1951aa4-1b81-413f-b246-a7db660d80e1"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PitchUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""52859337-529d-4415-ba82-c8d329500c12"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PitchDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5ba30651-0e48-4de5-82a7-d9f660df4042"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RollRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9797ed4c-8a1a-4224-bcb5-56a7c29af417"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RollLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""042bb664-9b06-49bb-9359-2f9e16cc2fd2"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""YawRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fa01cbb8-a087-4aff-ad42-01e367c3ab78"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""YawLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""45dda3e7-b1e0-4e8a-8da5-962205ae8a77"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cc7e4f64-3e55-4505-80d5-99593b10740e"",
                    ""path"": ""<Joystick>/stick/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Front/Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d5dc517a-812b-4374-8f9c-dd32331b91d4"",
                    ""path"": ""<Joystick>/stick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Yaw1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""381d774b-34ab-4100-9b5a-5615373518a8"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Handbrake"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e4d11cef-9497-4070-882a-d08c597d7c5e"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5083dd48-f4b3-4f88-bc83-08df2125d6fb"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bbd930d0-3541-4ef6-9af8-f0697882e384"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Throttle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Plane_Action_Map
        m_Plane_Action_Map = asset.FindActionMap("Plane_Action_Map", throwIfNotFound: true);
        m_Plane_Action_Map_PitchUp = m_Plane_Action_Map.FindAction("PitchUp", throwIfNotFound: true);
        m_Plane_Action_Map_PitchDown = m_Plane_Action_Map.FindAction("PitchDown", throwIfNotFound: true);
        m_Plane_Action_Map_RollRight = m_Plane_Action_Map.FindAction("RollRight", throwIfNotFound: true);
        m_Plane_Action_Map_RollLeft = m_Plane_Action_Map.FindAction("RollLeft", throwIfNotFound: true);
        m_Plane_Action_Map_YawRight = m_Plane_Action_Map.FindAction("YawRight", throwIfNotFound: true);
        m_Plane_Action_Map_YawLeft = m_Plane_Action_Map.FindAction("YawLeft", throwIfNotFound: true);
        m_Plane_Action_Map_Left = m_Plane_Action_Map.FindAction("Left", throwIfNotFound: true);
        m_Plane_Action_Map_FrontBack = m_Plane_Action_Map.FindAction("Front/Back", throwIfNotFound: true);
        m_Plane_Action_Map_Yaw1 = m_Plane_Action_Map.FindAction("Yaw1", throwIfNotFound: true);
        m_Plane_Action_Map_Handbrake = m_Plane_Action_Map.FindAction("Handbrake", throwIfNotFound: true);
        m_Plane_Action_Map_Look = m_Plane_Action_Map.FindAction("Look", throwIfNotFound: true);
        m_Plane_Action_Map_Interact = m_Plane_Action_Map.FindAction("Interact", throwIfNotFound: true);
        m_Plane_Action_Map_Throttle = m_Plane_Action_Map.FindAction("Throttle", throwIfNotFound: true);
    }

    ~@Plane_Controls()
    {
        UnityEngine.Debug.Assert(!m_Plane_Action_Map.enabled, "This will cause a leak and performance issues, Plane_Controls.Plane_Action_Map.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Plane_Action_Map
    private readonly InputActionMap m_Plane_Action_Map;
    private List<IPlane_Action_MapActions> m_Plane_Action_MapActionsCallbackInterfaces = new List<IPlane_Action_MapActions>();
    private readonly InputAction m_Plane_Action_Map_PitchUp;
    private readonly InputAction m_Plane_Action_Map_PitchDown;
    private readonly InputAction m_Plane_Action_Map_RollRight;
    private readonly InputAction m_Plane_Action_Map_RollLeft;
    private readonly InputAction m_Plane_Action_Map_YawRight;
    private readonly InputAction m_Plane_Action_Map_YawLeft;
    private readonly InputAction m_Plane_Action_Map_Left;
    private readonly InputAction m_Plane_Action_Map_FrontBack;
    private readonly InputAction m_Plane_Action_Map_Yaw1;
    private readonly InputAction m_Plane_Action_Map_Handbrake;
    private readonly InputAction m_Plane_Action_Map_Look;
    private readonly InputAction m_Plane_Action_Map_Interact;
    private readonly InputAction m_Plane_Action_Map_Throttle;
    /// <summary>
    /// Provides access to input actions defined in input action map "Plane_Action_Map".
    /// </summary>
    public struct Plane_Action_MapActions
    {
        private @Plane_Controls m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public Plane_Action_MapActions(@Plane_Controls wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Plane_Action_Map/PitchUp".
        /// </summary>
        public InputAction @PitchUp => m_Wrapper.m_Plane_Action_Map_PitchUp;
        /// <summary>
        /// Provides access to the underlying input action "Plane_Action_Map/PitchDown".
        /// </summary>
        public InputAction @PitchDown => m_Wrapper.m_Plane_Action_Map_PitchDown;
        /// <summary>
        /// Provides access to the underlying input action "Plane_Action_Map/RollRight".
        /// </summary>
        public InputAction @RollRight => m_Wrapper.m_Plane_Action_Map_RollRight;
        /// <summary>
        /// Provides access to the underlying input action "Plane_Action_Map/RollLeft".
        /// </summary>
        public InputAction @RollLeft => m_Wrapper.m_Plane_Action_Map_RollLeft;
        /// <summary>
        /// Provides access to the underlying input action "Plane_Action_Map/YawRight".
        /// </summary>
        public InputAction @YawRight => m_Wrapper.m_Plane_Action_Map_YawRight;
        /// <summary>
        /// Provides access to the underlying input action "Plane_Action_Map/YawLeft".
        /// </summary>
        public InputAction @YawLeft => m_Wrapper.m_Plane_Action_Map_YawLeft;
        /// <summary>
        /// Provides access to the underlying input action "Plane_Action_Map/Left".
        /// </summary>
        public InputAction @Left => m_Wrapper.m_Plane_Action_Map_Left;
        /// <summary>
        /// Provides access to the underlying input action "Plane_Action_Map/FrontBack".
        /// </summary>
        public InputAction @FrontBack => m_Wrapper.m_Plane_Action_Map_FrontBack;
        /// <summary>
        /// Provides access to the underlying input action "Plane_Action_Map/Yaw1".
        /// </summary>
        public InputAction @Yaw1 => m_Wrapper.m_Plane_Action_Map_Yaw1;
        /// <summary>
        /// Provides access to the underlying input action "Plane_Action_Map/Handbrake".
        /// </summary>
        public InputAction @Handbrake => m_Wrapper.m_Plane_Action_Map_Handbrake;
        /// <summary>
        /// Provides access to the underlying input action "Plane_Action_Map/Look".
        /// </summary>
        public InputAction @Look => m_Wrapper.m_Plane_Action_Map_Look;
        /// <summary>
        /// Provides access to the underlying input action "Plane_Action_Map/Interact".
        /// </summary>
        public InputAction @Interact => m_Wrapper.m_Plane_Action_Map_Interact;
        /// <summary>
        /// Provides access to the underlying input action "Plane_Action_Map/Throttle".
        /// </summary>
        public InputAction @Throttle => m_Wrapper.m_Plane_Action_Map_Throttle;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Plane_Action_Map; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="Plane_Action_MapActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(Plane_Action_MapActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="Plane_Action_MapActions" />
        public void AddCallbacks(IPlane_Action_MapActions instance)
        {
            if (instance == null || m_Wrapper.m_Plane_Action_MapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Plane_Action_MapActionsCallbackInterfaces.Add(instance);
            @PitchUp.started += instance.OnPitchUp;
            @PitchUp.performed += instance.OnPitchUp;
            @PitchUp.canceled += instance.OnPitchUp;
            @PitchDown.started += instance.OnPitchDown;
            @PitchDown.performed += instance.OnPitchDown;
            @PitchDown.canceled += instance.OnPitchDown;
            @RollRight.started += instance.OnRollRight;
            @RollRight.performed += instance.OnRollRight;
            @RollRight.canceled += instance.OnRollRight;
            @RollLeft.started += instance.OnRollLeft;
            @RollLeft.performed += instance.OnRollLeft;
            @RollLeft.canceled += instance.OnRollLeft;
            @YawRight.started += instance.OnYawRight;
            @YawRight.performed += instance.OnYawRight;
            @YawRight.canceled += instance.OnYawRight;
            @YawLeft.started += instance.OnYawLeft;
            @YawLeft.performed += instance.OnYawLeft;
            @YawLeft.canceled += instance.OnYawLeft;
            @Left.started += instance.OnLeft;
            @Left.performed += instance.OnLeft;
            @Left.canceled += instance.OnLeft;
            @FrontBack.started += instance.OnFrontBack;
            @FrontBack.performed += instance.OnFrontBack;
            @FrontBack.canceled += instance.OnFrontBack;
            @Yaw1.started += instance.OnYaw1;
            @Yaw1.performed += instance.OnYaw1;
            @Yaw1.canceled += instance.OnYaw1;
            @Handbrake.started += instance.OnHandbrake;
            @Handbrake.performed += instance.OnHandbrake;
            @Handbrake.canceled += instance.OnHandbrake;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
            @Throttle.started += instance.OnThrottle;
            @Throttle.performed += instance.OnThrottle;
            @Throttle.canceled += instance.OnThrottle;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="Plane_Action_MapActions" />
        private void UnregisterCallbacks(IPlane_Action_MapActions instance)
        {
            @PitchUp.started -= instance.OnPitchUp;
            @PitchUp.performed -= instance.OnPitchUp;
            @PitchUp.canceled -= instance.OnPitchUp;
            @PitchDown.started -= instance.OnPitchDown;
            @PitchDown.performed -= instance.OnPitchDown;
            @PitchDown.canceled -= instance.OnPitchDown;
            @RollRight.started -= instance.OnRollRight;
            @RollRight.performed -= instance.OnRollRight;
            @RollRight.canceled -= instance.OnRollRight;
            @RollLeft.started -= instance.OnRollLeft;
            @RollLeft.performed -= instance.OnRollLeft;
            @RollLeft.canceled -= instance.OnRollLeft;
            @YawRight.started -= instance.OnYawRight;
            @YawRight.performed -= instance.OnYawRight;
            @YawRight.canceled -= instance.OnYawRight;
            @YawLeft.started -= instance.OnYawLeft;
            @YawLeft.performed -= instance.OnYawLeft;
            @YawLeft.canceled -= instance.OnYawLeft;
            @Left.started -= instance.OnLeft;
            @Left.performed -= instance.OnLeft;
            @Left.canceled -= instance.OnLeft;
            @FrontBack.started -= instance.OnFrontBack;
            @FrontBack.performed -= instance.OnFrontBack;
            @FrontBack.canceled -= instance.OnFrontBack;
            @Yaw1.started -= instance.OnYaw1;
            @Yaw1.performed -= instance.OnYaw1;
            @Yaw1.canceled -= instance.OnYaw1;
            @Handbrake.started -= instance.OnHandbrake;
            @Handbrake.performed -= instance.OnHandbrake;
            @Handbrake.canceled -= instance.OnHandbrake;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
            @Throttle.started -= instance.OnThrottle;
            @Throttle.performed -= instance.OnThrottle;
            @Throttle.canceled -= instance.OnThrottle;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="Plane_Action_MapActions.UnregisterCallbacks(IPlane_Action_MapActions)" />.
        /// </summary>
        /// <seealso cref="Plane_Action_MapActions.UnregisterCallbacks(IPlane_Action_MapActions)" />
        public void RemoveCallbacks(IPlane_Action_MapActions instance)
        {
            if (m_Wrapper.m_Plane_Action_MapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="Plane_Action_MapActions.AddCallbacks(IPlane_Action_MapActions)" />
        /// <seealso cref="Plane_Action_MapActions.RemoveCallbacks(IPlane_Action_MapActions)" />
        /// <seealso cref="Plane_Action_MapActions.UnregisterCallbacks(IPlane_Action_MapActions)" />
        public void SetCallbacks(IPlane_Action_MapActions instance)
        {
            foreach (var item in m_Wrapper.m_Plane_Action_MapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Plane_Action_MapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="Plane_Action_MapActions" /> instance referencing this action map.
    /// </summary>
    public Plane_Action_MapActions @Plane_Action_Map => new Plane_Action_MapActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Plane_Action_Map" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="Plane_Action_MapActions.AddCallbacks(IPlane_Action_MapActions)" />
    /// <seealso cref="Plane_Action_MapActions.RemoveCallbacks(IPlane_Action_MapActions)" />
    public interface IPlane_Action_MapActions
    {
        /// <summary>
        /// Method invoked when associated input action "PitchUp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPitchUp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "PitchDown" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPitchDown(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RollRight" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRollRight(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RollLeft" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRollLeft(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "YawRight" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnYawRight(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "YawLeft" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnYawLeft(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Left" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeft(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Front/Back" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFrontBack(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Yaw1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnYaw1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Handbrake" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnHandbrake(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Look" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLook(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Interact" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnInteract(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Throttle" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnThrottle(InputAction.CallbackContext context);
    }
}
