//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.0
//     from Packages/com.n04h.techartlibrary/Base/Scripts/NewInputSystem/ControllerInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Packages/com.n04h.techartlibrary/Base/Scripts/NewInputSystem/ControllerInputs.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @ControllerInputs: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @ControllerInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ControllerInputs"",
    ""maps"": [
        {
            ""name"": ""ControllerActionMap"",
            ""id"": ""582292bb-1c2b-4e73-b48a-6b641e5831b7"",
            ""actions"": [
                {
                    ""name"": ""RightJoystick"",
                    ""type"": ""Value"",
                    ""id"": ""f6b756b7-e6d9-42b9-b8b2-0104de8fa069"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftJoystick"",
                    ""type"": ""Value"",
                    ""id"": ""91507e2b-3efd-4943-8eef-487c65bd578d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightUpButton"",
                    ""type"": ""Button"",
                    ""id"": ""c6310160-75ee-4fa2-8c48-edd99ad5a9e1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightRightButton"",
                    ""type"": ""Button"",
                    ""id"": ""0f5a4705-406d-47ee-9268-55c44393d32f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RigthLeftButton"",
                    ""type"": ""Button"",
                    ""id"": ""88c34178-07eb-47da-8ff2-66ab2eefb9a6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightDownButton"",
                    ""type"": ""Button"",
                    ""id"": ""45ffcb56-17a3-4382-ac54-394f43ac9953"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftUpButton"",
                    ""type"": ""Button"",
                    ""id"": ""a6198ac7-549e-4457-b5d6-6b58e5cb40e4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftRightButton"",
                    ""type"": ""Button"",
                    ""id"": ""100d03f9-0ca0-46e6-85db-f09b2c03593a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftLeftButton"",
                    ""type"": ""Button"",
                    ""id"": ""81c7d3bc-c0de-43c1-8973-de09aa3b5c7e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftDownButton"",
                    ""type"": ""Button"",
                    ""id"": ""122cbd43-325d-4c57-be1b-7fd179f8c50d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""R1"",
                    ""type"": ""Button"",
                    ""id"": ""ad854f0f-f79c-4941-94b9-7c817ff74388"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""R2"",
                    ""type"": ""Button"",
                    ""id"": ""5c2ba992-a038-46f3-b1aa-d1b8b08bee88"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""L1"",
                    ""type"": ""Button"",
                    ""id"": ""3e0ee503-71b7-4a80-b67a-6b0cfe4f89f3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""L2"",
                    ""type"": ""Button"",
                    ""id"": ""51b269f8-9b4a-402f-aa2d-e81e11b3a693"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""aa7bb754-3526-4bf1-877b-e966a8c9a4cb"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightJoystick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2cfa51a0-f725-4624-ba78-8dd00da81d6e"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftJoystick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f8784c9f-6242-4fa2-9ff0-1150e86f6377"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightUpButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""064bd57f-fc9f-4658-ad28-96b71a7cb1c3"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftUpButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ace5de18-ee63-4c6a-acfb-5b644e309087"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftRightButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""baff2985-a789-4cdb-92a0-f81a8ca010d5"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftLeftButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c674fb09-59d7-4bfa-bb51-bc19e1cf347f"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftDownButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e31bf627-81ec-4ae9-babc-7ae258f6578e"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightRightButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""05b9d25c-180b-4390-9600-47a50f12ec22"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RigthLeftButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d1d8cb32-cc87-4a20-821a-70ee389e7ae7"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightDownButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""488ac345-a5a2-4bb5-bf8f-d6f9109589f2"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""R1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b8546378-5a53-4c16-bc32-834cd0c8937a"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""R2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6903ebfd-e6f8-4c60-b07b-a49e8626a76b"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""L1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3f723afd-3666-405b-a7ac-9667f36788cc"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""L2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Gampad Control Scheme"",
            ""bindingGroup"": ""Gampad Control Scheme"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // ControllerActionMap
        m_ControllerActionMap = asset.FindActionMap("ControllerActionMap", throwIfNotFound: true);
        m_ControllerActionMap_RightJoystick = m_ControllerActionMap.FindAction("RightJoystick", throwIfNotFound: true);
        m_ControllerActionMap_LeftJoystick = m_ControllerActionMap.FindAction("LeftJoystick", throwIfNotFound: true);
        m_ControllerActionMap_RightUpButton = m_ControllerActionMap.FindAction("RightUpButton", throwIfNotFound: true);
        m_ControllerActionMap_RightRightButton = m_ControllerActionMap.FindAction("RightRightButton", throwIfNotFound: true);
        m_ControllerActionMap_RigthLeftButton = m_ControllerActionMap.FindAction("RigthLeftButton", throwIfNotFound: true);
        m_ControllerActionMap_RightDownButton = m_ControllerActionMap.FindAction("RightDownButton", throwIfNotFound: true);
        m_ControllerActionMap_LeftUpButton = m_ControllerActionMap.FindAction("LeftUpButton", throwIfNotFound: true);
        m_ControllerActionMap_LeftRightButton = m_ControllerActionMap.FindAction("LeftRightButton", throwIfNotFound: true);
        m_ControllerActionMap_LeftLeftButton = m_ControllerActionMap.FindAction("LeftLeftButton", throwIfNotFound: true);
        m_ControllerActionMap_LeftDownButton = m_ControllerActionMap.FindAction("LeftDownButton", throwIfNotFound: true);
        m_ControllerActionMap_R1 = m_ControllerActionMap.FindAction("R1", throwIfNotFound: true);
        m_ControllerActionMap_R2 = m_ControllerActionMap.FindAction("R2", throwIfNotFound: true);
        m_ControllerActionMap_L1 = m_ControllerActionMap.FindAction("L1", throwIfNotFound: true);
        m_ControllerActionMap_L2 = m_ControllerActionMap.FindAction("L2", throwIfNotFound: true);
    }

    ~@ControllerInputs()
    {
        UnityEngine.Debug.Assert(!m_ControllerActionMap.enabled, "This will cause a leak and performance issues, ControllerInputs.ControllerActionMap.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ControllerActionMap
    private readonly InputActionMap m_ControllerActionMap;
    private List<IControllerActionMapActions> m_ControllerActionMapActionsCallbackInterfaces = new List<IControllerActionMapActions>();
    private readonly InputAction m_ControllerActionMap_RightJoystick;
    private readonly InputAction m_ControllerActionMap_LeftJoystick;
    private readonly InputAction m_ControllerActionMap_RightUpButton;
    private readonly InputAction m_ControllerActionMap_RightRightButton;
    private readonly InputAction m_ControllerActionMap_RigthLeftButton;
    private readonly InputAction m_ControllerActionMap_RightDownButton;
    private readonly InputAction m_ControllerActionMap_LeftUpButton;
    private readonly InputAction m_ControllerActionMap_LeftRightButton;
    private readonly InputAction m_ControllerActionMap_LeftLeftButton;
    private readonly InputAction m_ControllerActionMap_LeftDownButton;
    private readonly InputAction m_ControllerActionMap_R1;
    private readonly InputAction m_ControllerActionMap_R2;
    private readonly InputAction m_ControllerActionMap_L1;
    private readonly InputAction m_ControllerActionMap_L2;
    /// <summary>
    /// Provides access to input actions defined in input action map "ControllerActionMap".
    /// </summary>
    public struct ControllerActionMapActions
    {
        private @ControllerInputs m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public ControllerActionMapActions(@ControllerInputs wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "ControllerActionMap/RightJoystick".
        /// </summary>
        public InputAction @RightJoystick => m_Wrapper.m_ControllerActionMap_RightJoystick;
        /// <summary>
        /// Provides access to the underlying input action "ControllerActionMap/LeftJoystick".
        /// </summary>
        public InputAction @LeftJoystick => m_Wrapper.m_ControllerActionMap_LeftJoystick;
        /// <summary>
        /// Provides access to the underlying input action "ControllerActionMap/RightUpButton".
        /// </summary>
        public InputAction @RightUpButton => m_Wrapper.m_ControllerActionMap_RightUpButton;
        /// <summary>
        /// Provides access to the underlying input action "ControllerActionMap/RightRightButton".
        /// </summary>
        public InputAction @RightRightButton => m_Wrapper.m_ControllerActionMap_RightRightButton;
        /// <summary>
        /// Provides access to the underlying input action "ControllerActionMap/RigthLeftButton".
        /// </summary>
        public InputAction @RigthLeftButton => m_Wrapper.m_ControllerActionMap_RigthLeftButton;
        /// <summary>
        /// Provides access to the underlying input action "ControllerActionMap/RightDownButton".
        /// </summary>
        public InputAction @RightDownButton => m_Wrapper.m_ControllerActionMap_RightDownButton;
        /// <summary>
        /// Provides access to the underlying input action "ControllerActionMap/LeftUpButton".
        /// </summary>
        public InputAction @LeftUpButton => m_Wrapper.m_ControllerActionMap_LeftUpButton;
        /// <summary>
        /// Provides access to the underlying input action "ControllerActionMap/LeftRightButton".
        /// </summary>
        public InputAction @LeftRightButton => m_Wrapper.m_ControllerActionMap_LeftRightButton;
        /// <summary>
        /// Provides access to the underlying input action "ControllerActionMap/LeftLeftButton".
        /// </summary>
        public InputAction @LeftLeftButton => m_Wrapper.m_ControllerActionMap_LeftLeftButton;
        /// <summary>
        /// Provides access to the underlying input action "ControllerActionMap/LeftDownButton".
        /// </summary>
        public InputAction @LeftDownButton => m_Wrapper.m_ControllerActionMap_LeftDownButton;
        /// <summary>
        /// Provides access to the underlying input action "ControllerActionMap/R1".
        /// </summary>
        public InputAction @R1 => m_Wrapper.m_ControllerActionMap_R1;
        /// <summary>
        /// Provides access to the underlying input action "ControllerActionMap/R2".
        /// </summary>
        public InputAction @R2 => m_Wrapper.m_ControllerActionMap_R2;
        /// <summary>
        /// Provides access to the underlying input action "ControllerActionMap/L1".
        /// </summary>
        public InputAction @L1 => m_Wrapper.m_ControllerActionMap_L1;
        /// <summary>
        /// Provides access to the underlying input action "ControllerActionMap/L2".
        /// </summary>
        public InputAction @L2 => m_Wrapper.m_ControllerActionMap_L2;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_ControllerActionMap; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="ControllerActionMapActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(ControllerActionMapActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="ControllerActionMapActions" />
        public void AddCallbacks(IControllerActionMapActions instance)
        {
            if (instance == null || m_Wrapper.m_ControllerActionMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ControllerActionMapActionsCallbackInterfaces.Add(instance);
            @RightJoystick.started += instance.OnRightJoystick;
            @RightJoystick.performed += instance.OnRightJoystick;
            @RightJoystick.canceled += instance.OnRightJoystick;
            @LeftJoystick.started += instance.OnLeftJoystick;
            @LeftJoystick.performed += instance.OnLeftJoystick;
            @LeftJoystick.canceled += instance.OnLeftJoystick;
            @RightUpButton.started += instance.OnRightUpButton;
            @RightUpButton.performed += instance.OnRightUpButton;
            @RightUpButton.canceled += instance.OnRightUpButton;
            @RightRightButton.started += instance.OnRightRightButton;
            @RightRightButton.performed += instance.OnRightRightButton;
            @RightRightButton.canceled += instance.OnRightRightButton;
            @RigthLeftButton.started += instance.OnRigthLeftButton;
            @RigthLeftButton.performed += instance.OnRigthLeftButton;
            @RigthLeftButton.canceled += instance.OnRigthLeftButton;
            @RightDownButton.started += instance.OnRightDownButton;
            @RightDownButton.performed += instance.OnRightDownButton;
            @RightDownButton.canceled += instance.OnRightDownButton;
            @LeftUpButton.started += instance.OnLeftUpButton;
            @LeftUpButton.performed += instance.OnLeftUpButton;
            @LeftUpButton.canceled += instance.OnLeftUpButton;
            @LeftRightButton.started += instance.OnLeftRightButton;
            @LeftRightButton.performed += instance.OnLeftRightButton;
            @LeftRightButton.canceled += instance.OnLeftRightButton;
            @LeftLeftButton.started += instance.OnLeftLeftButton;
            @LeftLeftButton.performed += instance.OnLeftLeftButton;
            @LeftLeftButton.canceled += instance.OnLeftLeftButton;
            @LeftDownButton.started += instance.OnLeftDownButton;
            @LeftDownButton.performed += instance.OnLeftDownButton;
            @LeftDownButton.canceled += instance.OnLeftDownButton;
            @R1.started += instance.OnR1;
            @R1.performed += instance.OnR1;
            @R1.canceled += instance.OnR1;
            @R2.started += instance.OnR2;
            @R2.performed += instance.OnR2;
            @R2.canceled += instance.OnR2;
            @L1.started += instance.OnL1;
            @L1.performed += instance.OnL1;
            @L1.canceled += instance.OnL1;
            @L2.started += instance.OnL2;
            @L2.performed += instance.OnL2;
            @L2.canceled += instance.OnL2;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="ControllerActionMapActions" />
        private void UnregisterCallbacks(IControllerActionMapActions instance)
        {
            @RightJoystick.started -= instance.OnRightJoystick;
            @RightJoystick.performed -= instance.OnRightJoystick;
            @RightJoystick.canceled -= instance.OnRightJoystick;
            @LeftJoystick.started -= instance.OnLeftJoystick;
            @LeftJoystick.performed -= instance.OnLeftJoystick;
            @LeftJoystick.canceled -= instance.OnLeftJoystick;
            @RightUpButton.started -= instance.OnRightUpButton;
            @RightUpButton.performed -= instance.OnRightUpButton;
            @RightUpButton.canceled -= instance.OnRightUpButton;
            @RightRightButton.started -= instance.OnRightRightButton;
            @RightRightButton.performed -= instance.OnRightRightButton;
            @RightRightButton.canceled -= instance.OnRightRightButton;
            @RigthLeftButton.started -= instance.OnRigthLeftButton;
            @RigthLeftButton.performed -= instance.OnRigthLeftButton;
            @RigthLeftButton.canceled -= instance.OnRigthLeftButton;
            @RightDownButton.started -= instance.OnRightDownButton;
            @RightDownButton.performed -= instance.OnRightDownButton;
            @RightDownButton.canceled -= instance.OnRightDownButton;
            @LeftUpButton.started -= instance.OnLeftUpButton;
            @LeftUpButton.performed -= instance.OnLeftUpButton;
            @LeftUpButton.canceled -= instance.OnLeftUpButton;
            @LeftRightButton.started -= instance.OnLeftRightButton;
            @LeftRightButton.performed -= instance.OnLeftRightButton;
            @LeftRightButton.canceled -= instance.OnLeftRightButton;
            @LeftLeftButton.started -= instance.OnLeftLeftButton;
            @LeftLeftButton.performed -= instance.OnLeftLeftButton;
            @LeftLeftButton.canceled -= instance.OnLeftLeftButton;
            @LeftDownButton.started -= instance.OnLeftDownButton;
            @LeftDownButton.performed -= instance.OnLeftDownButton;
            @LeftDownButton.canceled -= instance.OnLeftDownButton;
            @R1.started -= instance.OnR1;
            @R1.performed -= instance.OnR1;
            @R1.canceled -= instance.OnR1;
            @R2.started -= instance.OnR2;
            @R2.performed -= instance.OnR2;
            @R2.canceled -= instance.OnR2;
            @L1.started -= instance.OnL1;
            @L1.performed -= instance.OnL1;
            @L1.canceled -= instance.OnL1;
            @L2.started -= instance.OnL2;
            @L2.performed -= instance.OnL2;
            @L2.canceled -= instance.OnL2;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="ControllerActionMapActions.UnregisterCallbacks(IControllerActionMapActions)" />.
        /// </summary>
        /// <seealso cref="ControllerActionMapActions.UnregisterCallbacks(IControllerActionMapActions)" />
        public void RemoveCallbacks(IControllerActionMapActions instance)
        {
            if (m_Wrapper.m_ControllerActionMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="ControllerActionMapActions.AddCallbacks(IControllerActionMapActions)" />
        /// <seealso cref="ControllerActionMapActions.RemoveCallbacks(IControllerActionMapActions)" />
        /// <seealso cref="ControllerActionMapActions.UnregisterCallbacks(IControllerActionMapActions)" />
        public void SetCallbacks(IControllerActionMapActions instance)
        {
            foreach (var item in m_Wrapper.m_ControllerActionMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ControllerActionMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="ControllerActionMapActions" /> instance referencing this action map.
    /// </summary>
    public ControllerActionMapActions @ControllerActionMap => new ControllerActionMapActions(this);
    private int m_GampadControlSchemeSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme GampadControlSchemeScheme
    {
        get
        {
            if (m_GampadControlSchemeSchemeIndex == -1) m_GampadControlSchemeSchemeIndex = asset.FindControlSchemeIndex("Gampad Control Scheme");
            return asset.controlSchemes[m_GampadControlSchemeSchemeIndex];
        }
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "ControllerActionMap" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="ControllerActionMapActions.AddCallbacks(IControllerActionMapActions)" />
    /// <seealso cref="ControllerActionMapActions.RemoveCallbacks(IControllerActionMapActions)" />
    public interface IControllerActionMapActions
    {
        /// <summary>
        /// Method invoked when associated input action "RightJoystick" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRightJoystick(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LeftJoystick" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeftJoystick(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RightUpButton" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRightUpButton(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RightRightButton" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRightRightButton(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RigthLeftButton" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRigthLeftButton(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RightDownButton" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRightDownButton(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LeftUpButton" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeftUpButton(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LeftRightButton" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeftRightButton(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LeftLeftButton" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeftLeftButton(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LeftDownButton" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeftDownButton(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "R1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnR1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "R2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnR2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "L1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnL1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "L2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnL2(InputAction.CallbackContext context);
    }
}
